services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: phoenix
      MINIO_ROOT_PASSWORD: analytics
    command: server --console-address ":9001" /data

volumes:
  minio_storage: {}
