services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: phoenix_mysql_dev
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
